const demoTopics=['Attention is a form of love','The architecture of a good morning','What makes an idea sticky?','A note you keep returning to','The space between signal and noise','How taste becomes a compass','The useful friction of boredom','What does enough feel like?'];
const $=s=>document.querySelector(s);let topics=[],notes={},recent=[],skipped=JSON.parse(localStorage.getItem('unpromptedSkipped')||'[]'),currentTopic='',topicWasPracticed=false,timer=null,remaining=0,planned=0,extensions=0,isSpinning=false;
window.addEventListener('DOMContentLoaded',()=>{const label=document.querySelector('#stateLabel');if(label&&label.textContent==='NO VAULT CONNECTED')label.textContent='READY WHEN YOU ARE'});
const sessionHistory=()=>JSON.parse(localStorage.getItem('unpromptedHistory')||'[]');const saveSession=()=>{const all=sessionHistory();all.push({date:new Date().toISOString(),topic:$('#summaryTopic').textContent,spoke:$('#statSpoke').textContent,planned:$('#statPlanned').textContent,extra:$('#statExtensions').textContent,rating:null});localStorage.setItem('unpromptedHistory',JSON.stringify(all));$('#sessionRating').hidden=false};new MutationObserver(()=>{if(!$('#summaryModal').hidden)saveSession()}).observe($('#summaryModal'),{attributes:true,attributeFilter:['hidden']});document.querySelectorAll('[data-session-rating]').forEach(b=>b.onclick=()=>{const all=sessionHistory();if(all.length){all[all.length-1].rating=+b.dataset.sessionRating;localStorage.setItem('unpromptedHistory',JSON.stringify(all));document.querySelectorAll('[data-session-rating]').forEach(x=>x.classList.toggle('selected',x===b));toast('Session rating saved')}});
$('#exportHistory').onclick=()=>{const md=sessionHistory().map(x=>`## ${x.date.slice(0,10)} · ${x.topic}\n\n- Spoke for: ${x.spoke}\n- Planned: ${x.planned}\n- Extra time: ${x.extra}\n- Session rating: ${x.rating||'Not rated'}\n`).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([md],{type:'text/markdown'}));a.download='Unprompted History.md';a.click();URL.revokeObjectURL(a.href)};
let settings={timer:60,spin:2200,weighted:true,dark:false,...JSON.parse(localStorage.getItem('unpromptedSettings')||'{}')};let ratings=JSON.parse(localStorage.getItem('unpromptedRatings')||'{}');let seen=JSON.parse(localStorage.getItem('unpromptedSeen')||'{}');
const fmt=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;const save=()=>localStorage.setItem('unpromptedSettings',JSON.stringify(settings));const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2200)};const state=(text,color='')=>{$('#stateLabel').textContent=text;$('#statusDot').style.backgroundColor={spinning:'#c58b2d',active:'#67a676',preview:'#9a98b0',ended:'#d47935',complete:'#5a86b8'}[color]||''};
function sync(){const has=!!currentTopic;$('#startBtn').disabled=!has||!!timer;document.querySelectorAll('.timer').forEach(b=>b.disabled=!!timer)}function renderRecent(){$('#recentList').innerHTML=recent.length?recent.slice(0,8).map(x=>`<div class="recent-item">${x}</div>`).join(''):'<div class="empty">Your spun topics will collect here.</div>'}function renderTopics(){$('#topicsList').innerHTML=topics.length?topics.map(t=>`<button class="topic-row">${t}</button>`).join(''):'<p>No topics loaded yet.</p>';document.querySelectorAll('.topic-row').forEach(b=>b.onclick=()=>selectTopic(b.textContent))}
function connect(list,label){topics=[...new Set(list)].filter(Boolean);$('#countLabel').textContent=`${topics.length} topics loaded` ;$('#vaultStatus').textContent=label||'Vault connected';$('.vault-status').classList.add('connected');$('#setupCard').classList.add('is-hidden');$('#connectedBar').classList.add('is-visible');$('#connectedName').textContent=label||'Vault connected';$('#connectedCount').textContent=`${topics.length} topics ready`;renderTopics();$('#topic').innerHTML=topics.length?'Your topics are ready<br><small>spin when you want a thread</small>':'No wikilinks found';state(topics.length?'READY WHEN YOU ARE':'NO TOPICS FOUND');sync()}
function selectTopic(t){currentTopic=t;$('#topic').textContent=t;$('#topicMeta').textContent='say the first thing that comes to mind';state('YOUR THREAD','active');sync()}
async function recordsFromDirectory(h){let a=[];for await(const e of h.values()){if(e.kind==='directory')a=a.concat(await recordsFromDirectory(e));else if(e.name.toLowerCase().endsWith('.md'))a.push({name:e.name,text:await(await e.getFile()).text()})}return a}async function processFiles(files,label){const zip=files.find(f=>f.name.toLowerCase().endsWith('.zip'));try{if(zip&&window.JSZip){const a=await JSZip.loadAsync(zip);files=await Promise.all(Object.values(a.files).filter(f=>!f.dir&&f.name.toLowerCase().endsWith('.md')).map(async f=>({name:f.name.split('/').pop(),text:await f.async('text')})))}else files=await Promise.all(files.filter(f=>f.name.toLowerCase().endsWith('.md')).map(async f=>({name:f.name,text:await f.text()})));notes={};files.forEach(f=>notes[f.name.replace(/\.md$/i,'').toLowerCase()]=f.text);connect(files.flatMap(f=>[...f.text.matchAll(/\[\[([^\]|#]+)(?:#[^\]|]+)?(?:\|[^\]]+)?\]\]/g)].map(m=>m[1].trim())),label||'Vault connected')}catch(e){toast('Could not read those files')}}
$('#browseBtn').onclick=async()=>{if(window.showDirectoryPicker){try{const h=await window.showDirectoryPicker({mode:'read'});return processFiles(await recordsFromDirectory(h),h.name)}catch(e){if(e.name==='AbortError')return}}$('#folderInput').click()};$('#folderInput').onchange=e=>processFiles([...e.target.files]);$('#filesBtn').onclick=()=>$('#filesInput').click();$('#filesInput').onchange=e=>processFiles([...e.target.files]);$('#changeVault').onclick=()=>{$('#setupCard').classList.remove('is-hidden');$('#connectedBar').classList.remove('is-visible')};
$('#countLabel').onclick=()=>{$('#topicsDrawer').classList.toggle('is-open');renderTopics()};$('#closeTopics').onclick=()=>$('#topicsDrawer').classList.remove('is-open');
function weighted(){if(!settings.weighted)return topics;return topics.flatMap(t=>{const age=Math.min(30,(Date.now()-(seen[t]||0))/86400000),weight=Math.max(1,(6-(ratings[t]||3))*(1+age/7));return Array(Math.ceil(weight)).fill(t)})}
$('#spinBtn').onclick=()=>{if(isSpinning)return;isSpinning=true;const pool=topics.length?weighted():demoTopics;let i=0;state('SPINNING…','spinning');$('#spinBtn').disabled=true;const id=setInterval(()=>{$('#topic').textContent=pool[Math.floor(Math.random()*pool.length)];if(++i>=Math.max(12,Math.round(settings.spin/90))){clearInterval(id);selectTopic(pool[Math.floor(Math.random()*pool.length)]);isSpinning=false;$('#spinBtn').disabled=false}},90)};
function endTimer(show=true,complete=false){clearInterval(timer);timer=null;$('#focusTimer').classList.remove('is-visible');$('#startBtn').textContent='Start timer';if(currentTopic&&planned){seen[currentTopic]=Date.now();localStorage.setItem('unpromptedSeen',JSON.stringify(seen));recent=[currentTopic,...recent.filter(x=>x!==currentTopic)].slice(0,20);renderRecent()}sync();if(show){const spoke=planned+extensions*30-remaining;$('#summaryTopic').textContent=currentTopic;$('#statSpoke').textContent=fmt(spoke);$('#statPlanned').textContent=fmt(planned);$('#statExtensions').textContent=`+${extensions*30} sec`;$('#statMode').textContent='Speaking practice';$('#summaryModal').hidden=false;state(complete?'SESSION COMPLETE':'SESSION ENDED',complete?'complete':'ended')}}
$('#startBtn').onclick=()=>{if(!currentTopic)return toast('Spin for a topic before starting the timer');remaining=settings.timer;planned=settings.timer;extensions=0;$('#focusTopic').textContent=currentTopic;$('#focusClock').textContent=fmt(remaining);$('#focusTimer').classList.add('is-visible');$('#startBtn').textContent='Timer running';timer=setInterval(()=>{remaining--;$('#focusClock').textContent=fmt(remaining);if(remaining<=0)endTimer(true,true)},1000);sync()};$('#addTime').onclick=()=>{if(timer){remaining+=30;extensions++;$('#focusClock').textContent=fmt(remaining)}};$('#finishTimer').onclick=()=>endTimer();$('#closeSummary').onclick=()=>$('#summaryModal').hidden=true;
document.querySelectorAll('.timer').forEach(b=>b.onclick=()=>{if(!timer){settings.timer=+b.dataset.time;save();document.querySelectorAll('.timer').forEach(x=>x.classList.remove('active'));b.classList.add('active')}});document.querySelectorAll('.mode').forEach(b=>b.remove());$('#resetBtn').onclick=()=>{if(timer)endTimer(false);currentTopic='';$('#summaryModal').hidden=true;state(topics.length?'READY WHEN YOU ARE':'NO VAULT CONNECTED');$('#topic').innerHTML=topics.length?'Your topics are ready<br><small>spin when you want a thread</small>':'Connect your vault<br><small>and your topics will appear here</small>';sync()};$('#clearBtn').onclick=()=>{recent=[];renderRecent()};
$('#settingsBtn').onclick=()=>$('#settingsModal').hidden=false;$('#closeSettings').onclick=()=>$('#settingsModal').hidden=true;$('#defaultTimer').value=settings.timer;$('#spinDuration').value=settings.spin;$('#weightedChoice').checked=settings.weighted;$('#darkMode').checked=settings.dark;document.body.classList.toggle('dark',settings.dark);$('#defaultTimer').onchange=e=>{settings.timer=+e.target.value;save();toast('Default timer saved')};$('#spinDuration').onchange=e=>{settings.spin=+e.target.value;save();toast('Spin duration saved')};$('#weightedChoice').onchange=e=>{settings.weighted=e.target.checked;save();toast('Topic weighting saved')};$('#darkMode').onchange=e=>{settings.dark=e.target.checked;document.body.classList.toggle('dark',settings.dark);save();toast('Theme saved')};$('#resetData').onclick=()=>{localStorage.removeItem('unpromptedRatings');localStorage.removeItem('unpromptedSeen');ratings={};seen={};toast('Ratings and topic history reset')};sync();
function renderSkipped(){const el=$('#skippedList');el.innerHTML=skipped.length?skipped.map(x=>`<button class="recent-item skipped-item">${x}</button>`).join(''):'<div class="empty">Topics you can return to later.</div>';el.querySelectorAll('.skipped-item').forEach(b=>b.onclick=()=>{selectTopic(b.textContent);skipped=skipped.filter(x=>x!==b.textContent);localStorage.setItem('unpromptedSkipped',JSON.stringify(skipped));renderSkipped()})}renderSkipped();
