const demoTopics=['Attention is a form of love','The architecture of a good morning','What makes an idea sticky?','A note you keep returning to','The space between signal and noise','How taste becomes a compass','The useful friction of boredom','A small system that changed you','What does “enough” feel like?','The future you are quietly building'];
let topics=[],recent=[],seconds=60,timer=null,mode='quick';
const $=s=>document.querySelector(s); const topicEl=$('#topic');
function notify(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function renderRecent(){const el=$('#recentList');el.innerHTML=recent.length?recent.slice(0,8).map(x=>`<div class="recent-item">${x}</div>`).join(''):'<div class="empty">Your spun topics will collect here.</div>'}
function connect(list,label){topics=[...new Set(list)].filter(Boolean);const name=label||'Vault connected';$('#countLabel').textContent=`${topics.length} topics loaded`;$('#vaultStatus').textContent=name;$('.vault-status').classList.add('connected');$('#setupCard').classList.add('is-hidden');$('#connectedBar').classList.add('is-visible');$('#connectedName').textContent=name;$('#connectedCount').textContent=`${topics.length} topics ready`;$('#setupCard').style.borderColor='#a9c4ad';topicEl.innerHTML='Your topics are ready<br><small>spin when you want a thread</small>';notify(`${topics.length} topics ready to explore`)}
async function readDirectory(handle){let texts=[];for await(const entry of handle.values()){if(entry.kind==='directory'){texts=texts.concat(await readDirectory(entry))}else if(entry.name.toLowerCase().endsWith('.md')){texts.push(await (await entry.getFile()).text())}}return texts}
async function processFiles(files,label){const zip=files.find(f=>f.name.toLowerCase().endsWith('.zip'));if(zip&&window.JSZip){const archive=await JSZip.loadAsync(zip);const texts=await Promise.all(Object.values(archive.files).filter(f=>!f.dir&&f.name.toLowerCase().endsWith('.md')).map(f=>f.async('text')));return connectFromTexts(texts,label||zip.name.replace(/\.zip$/i,''))}const md=files.filter(f=>f.name.toLowerCase().endsWith('.md'));const texts=await Promise.all(md.map(f=>f.text()));connectFromTexts(texts,label||md[0]?.webkitRelativePath.split('/')[0]||'Vault connected')}
$('#browseBtn').onclick=async()=>{if(window.showDirectoryPicker){try{const handle=await window.showDirectoryPicker({mode:'read'});const texts=await readDirectory(handle);connectFromTexts(texts,handle.name||'Vault connected');return}catch(error){if(error.name==='AbortError')return}}$('#folderInput').click()};
$('#folderInput').onchange=async e=>processFiles([...e.target.files]);$('#filesBtn').onclick=()=>$('#filesInput').click();$('#filesInput').onchange=async e=>processFiles([...e.target.files]);
if(!window.showDirectoryPicker)$('#pickerHelp').style.display='block';
function connectFromTexts(texts,label){const matches=texts.flatMap(t=>[...t.matchAll(/\[\[([^\]|#]+)(?:#[^\]|]+)?(?:\|[^\]]+)?\]\]/g)].map(m=>m[1].trim()));connect(matches,label);$('#topicMeta').textContent=matches.length?`${texts.length} Markdown files scanned · local only`:`${texts.length} Markdown files scanned · no [[wikilinks]] found`}
$('#changeVault').onclick=()=>{$('#setupCard').classList.remove('is-hidden');$('#connectedBar').classList.remove('is-visible');window.scrollTo({top:document.querySelector('#setupCard').offsetTop-24,behavior:'smooth'})};
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;notify(mode==='deep'?'Take the long way around':'Keep it light and quick')});document.querySelectorAll('.timer').forEach(b=>b.onclick=()=>{document.querySelectorAll('.timer').forEach(x=>x.classList.remove('active'));b.classList.add('active');seconds=+b.dataset.time;$('#stateLabel').textContent='READY WHEN YOU ARE'});
$('#spinBtn').onclick=()=>{const pool=topics.length?topics:demoTopics;const pick=pool[Math.floor(Math.random()*pool.length)];topicEl.textContent=pick;$('#topicMeta').textContent=mode==='deep'?'follow the idea · no wrong turns':'say the first thing that comes to mind';$('#stateLabel').textContent='YOUR THREAD';recent.unshift(pick);renderRecent();clearInterval(timer);let left=seconds;const active=$('.timer.active');active.textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;timer=setInterval(()=>{left--;active.textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;if(left<=0){clearInterval(timer);$('#stateLabel').textContent='TIME TO LAND THE PLANE';notify('One minute. What did you notice?')}},1000)};$('#resetBtn').onclick=()=>{clearInterval(timer);recent=[];renderRecent();topicEl.innerHTML=topics.length?'Your topics are ready<br><small>spin when you want a thread</small>':'Connect your vault<br><small>and your topics will appear here</small>';$('#stateLabel').textContent='READY WHEN YOU ARE';notify('Session cleared')};$('#clearBtn').onclick=()=>{recent=[];renderRecent()};$('#settingsBtn').onclick=()=>notify('Settings are coming to the local beta')
